## Part 1: Preprocessing

In [3]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [4]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [21]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

In [22]:
# Create a list of at least 10 column names to use as X data
x_columns = ['Age', 'BusinessTravel', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction',
             'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'MaritalStatus', 'NumCompaniesWorked',
             'OverTime']

# Create x_df using your selected columns
x_df = attrition_df[x_columns]

# Show the data types for x_df
print(x_df.dtypes)

Age                         int64
BusinessTravel             object
DistanceFromHome            int64
Education                   int64
EnvironmentSatisfaction     int64
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                    object
MaritalStatus              object
NumCompaniesWorked          int64
OverTime                   object
dtype: object

In [23]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_df, y_df, test_size=0.2, random_state=42)

# Display the shapes of the resulting datasets
print("x_train shape:", x_train.shape)
print("x_test shape:", x_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

x_train shape: (1176, 12)
x_test shape: (294, 12)
y_train shape: (1176, 2)
y_test shape: (294, 2)

In [24]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
# Identify non-numeric columns
non_numeric_columns = x_df.select_dtypes(include=['object']).columns
print("Non-numeric columns:", non_numeric_columns)

# Convert categorical columns to numeric using one-hot encoding
x_df_numeric = pd.get_dummies(x_df, columns=non_numeric_columns)

# Ensure all columns are now numeric
print("Data types of x_df_numeric:\n", x_df_numeric.dtypes)
print("First few rows of x_df_numeric:\n", x_df_numeric.head())

Non-numeric columns: Index(['BusinessTravel', 'JobRole', 'MaritalStatus', 'OverTime'], dtype='object')
Data types of x_df_numeric:
 Age                                  int64
DistanceFromHome                     int64
Education                            int64
EnvironmentSatisfaction              int64
HourlyRate                           int64
JobInvolvement                       int64
JobLevel                             int64
NumCompaniesWorked                   int64
BusinessTravel_Non-Travel             bool
BusinessTravel_Travel_Frequently      bool
BusinessTravel_Travel_Rarely          bool
JobRole_Healthcare Representative     bool
JobRole_Human Resources               bool
JobRole_Laboratory Technician         bool
JobRole_Manager                       bool
JobRole_Manufacturing Director        bool
JobRole_Research Director             bool
JobRole_Research Scientist            bool
JobRole_Sales Executive               bool
JobRole_Sales Representative          bool
MaritalStatus_Divorced                bool
MaritalStatus_Married                 bool
MaritalStatus_Single                  bool
OverTime_No                           bool
OverTime_Yes                          bool
dtype: object
First few rows of x_df_numeric:
    Age  DistanceFromHome  Education  EnvironmentSatisfaction  HourlyRate  \
0   41                 1          2                        2          94
1   49                 8          1                        3          61
2   37                 2          2                        4          92
3   33                 3          4                        4          56
4   27                 2          1                        1          40

   JobInvolvement  JobLevel  NumCompaniesWorked  BusinessTravel_Non-Travel  \
0               3         2                   8                      False
1               2         2                   1                      False
2               2         1                   6                      False
3               3         1                   1                      False
4               3         1                   9                      False

   BusinessTravel_Travel_Frequently  ...  JobRole_Manufacturing Director  \
0                             False  ...                           False
1                              True  ...                           False
2                             False  ...                           False
3                              True  ...                           False
4                             False  ...                           False

   JobRole_Research Director  JobRole_Research Scientist  \
0                      False                       False
1                      False                        True
2                      False                       False
3                      False                        True
4                      False                       False

   JobRole_Sales Executive  JobRole_Sales Representative  \
0                     True                         False
1                    False                         False
2                    False                         False
3                    False                         False
4                    False                         False

   MaritalStatus_Divorced  MaritalStatus_Married  MaritalStatus_Single  \
0                   False                  False                  True
1                   False                   True                 False
2                   False                  False                  True
3                   False                   True                 False
4                   False                   True                 False

   OverTime_No  OverTime_Yes
0        False          True
1         True         False
2        False          True
3        False          True
4         True         False

[5 rows x 25 columns]

In [26]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(x_train)

# Scale the training and testing data
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Optionally, you can convert the scaled data back to DataFrames
x_train_scaled_df = pd.DataFrame(x_train_scaled, columns=x_train.columns)
x_test_scaled_df = pd.DataFrame(x_test_scaled, columns=x_test.columns)

# Display the first few rows of the scaled training data
print("First few rows of the scaled training data:\n", x_train_scaled_df.head())

ValueError: could not convert string to float: 'Travel_Rarely'

In [10]:
# Create a OneHotEncoder for the Department column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data

In [11]:
# Create a OneHotEncoder for the Attrition column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data

## Create, Compile, and Train the Model

In [12]:
# Find the number of columns in the X training data


# Create the input layer


# Create at least two shared layers

In [13]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer

In [14]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer

In [15]:
# Create the model


# Compile the model


# Summarize the model

In [16]:
# Train the model

In [17]:
# Evaluate the model with the testing data

In [18]:
# Print the accuracy for both department and attrition

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1.
2.
3.